@url=http://localhost:3000

### Listar todos
GET {{url}}/pacientes

### Buscar por ID
GET {{url}}/pacientes/1

### Crear paciente
POST {{url}}/pacientes
Content-Type: application/json

{
  "nombre": "tiago",
  "apellido": "yoppa",
  "dni": "45470185",
  "fecha_nacimiento": "2004-01-14",
  "obra_social": "OSDE"
}

### Eliminar paciente
DELETE {{url}}/pacientes/1