@url = http://localhost:3000

###Cambiar esto por el token
@token = {{auth.login.response.body.token}}

### Listar todos los turnos
GET {{url}}/turnos
Authorization: Bearer {{token}}

### Buscar turno por ID  
GET {{url}}/turnos/1
Authorization: Bearer {{token}}

### Crear un turno
# @name createAppointment
POST {{url}}/turnos
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "paciente_id": 1,
  "medico_id": 1,
  "fecha": "2025-01-20",
  "hora": "12:30",
  "estado": "pendiente",
  "observaciones": "Primera consulta"
}

### Actualizar estado de un turno
PUT {{url}}/turnos/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "estado": "atendido",
  "observaciones": "Paciente atendido correctamente"
}

### Eliminar turno
DELETE {{url}}/turnos/1
Authorization: Bearer {{token}}